version: 2

project_name: sysup

builds:
  - id: sysup
    dir: sysup
    main: ./cmd/sysup
    binary: sysup
    ldflags:
      - -s -w -X sysup/internal/selfupdate.Version=v{{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  - id: sysup-worker
    dir: sysup
    main: ./cmd/sysup-worker
    binary: sysup-worker
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: sysup
    ids: [sysup]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

  - id: sysup-worker
    ids: [sysup-worker]
    formats: [tar.gz]
    name_template: >-
      sysup-worker_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: luysfernnando
    name: linux_scripts
